spring:
  profiles:
    active: dev
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dhht
    username: root
    password: 123456
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect:  org.hibernate.dialect.MySQL5Dialect
       current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext  #最后一个比较重要
       
       
    
    
  
 
 